# frozen_string_literal: true

# Aggregator for the generated REST resource layer (scripts/generate_rest.py).
#
# Requires the generated per-resource classes, the per-namespace containers, and
# the ResourceTree module the hand RestClient composes. Load order matters: the
# hand bases (BaseResource / CrudResource / CrudWithAddresses, in http_client.rb)
# must be loaded first (rest_client.rb requires http_client before this file),
# then the generated Fabric bases, then the resource classes that inherit them,
# then the containers, then the ResourceTree that references every class.
#
# This file itself is HAND-written (a stable require manifest); the files it
# loads are all generated + regenerated by `python3 scripts/generate_rest.py`.

require_relative 'generated/_fabric_bases'

# Every generated resource + container file except the fabric bases (required
# above) and resource_tree (required last, it references all classes). Wrapped
# in a lambda so the skip-list literal and loop var don't leak a top-level
# constant/local.
lambda do
  explicit = %w[_fabric_bases resource_tree].freeze
  Dir[File.join(__dir__, 'generated', '*.rb')].each do |f|
    next if explicit.include?(File.basename(f, '.rb'))

    require f
  end
end.call

require_relative 'generated/resource_tree'
