kind: pipeline
name: default

steps:
- name: test
  image: ruby:2.6
  commands:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec

- name: test 2.7
  image: ruby:2.7
  commands:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec

- name: test 3.0
  image: ruby:3.0
  commands:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec

- name: test 3.1
  image: ruby:3.1
  commands:
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - bundle exec rspec

trigger:
  event: push
