# frozen_string_literal: true

# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: signalwire-ruby 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = 'signalwire-ruby'
  s.version = '1.0.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']
  s.authors = ['SignalWire Team']
  s.date = '2018-09-20'
  s.email = 'open.source@signalwire.com'
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.document',
    '.rspec',
    '.rubocop.yml',
    'Gemfile',
    'Gemfile.lock',
    'Guardfile',
    'LICENSE.txt',
    'Rakefile',
    'VERSION',
    'lib/signalwire/rest/client.rb',
    'lib/signalwire/sdk.rb',
    'lib/signalwire/sdk/configuration.rb',
    'lib/signalwire/sdk/domain.rb',
    'lib/signalwire/sdk/twilio_set_host.rb',
    'lib/signalwire/sdk/voice_response.rb',
    'signalwire-client.gemspec',
    'spec/signalwire/rest/client_spec.rb',
    'spec/signalwire/sdk/configuration_spec.rb',
    'spec/signalwire/sdk/voice_response_spec.rb',
    'spec/signalwire/sdk_spec.rb',
    'spec/spec_helper.rb'
  ]
  s.homepage = 'http://github.com/signalwire/signalwire-ruby'
  s.licenses = ['MIT']
  s.rubygems_version = '2.7.3'
  s.summary = 'Ruby client for Signalwire'

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('twilio-ruby', ['~> 5.0'])
      s.add_development_dependency('bundler', ['~> 1.0'])
      s.add_development_dependency('bundler-audit', ['>= 0'])
      s.add_development_dependency('guard-rspec', ['>= 0'])
      s.add_development_dependency('juwelier', ['~> 2.1.0'])
      s.add_development_dependency('rdoc', ['~> 3.12'])
      s.add_development_dependency('rspec', ['~> 3.5.0'])
      s.add_development_dependency('rubocop', ['>= 0'])
      s.add_development_dependency('simplecov', ['>= 0'])
      s.add_development_dependency('webmock', ['>= 0'])
    else
      s.add_dependency('rdoc', ['~> 3.12'])
      s.add_dependency('rdoc', ['~> 3.12'])
      s.add_dependency('rdoc', ['~> 3.12'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('simplecov', ['>= 0'])
      s.add_dependency('twilio-ruby', ['~> 5.0'])
      s.add_dependency('webmock', ['>= 0'])
    end
  else
    s.add_dependency('bundler', ['~> 1.0'])
    s.add_dependency('bundler-audit', ['>= 0'])
    s.add_dependency('guard-rspec', ['>= 0'])
    s.add_dependency('juwelier', ['~> 2.1.0'])
    s.add_dependency('rspec', ['~> 3.5.0'])
    s.add_dependency('rubocop', ['>= 0'])
    s.add_dependency('twilio-ruby', ['~> 5.0'])
    s.add_dependency('twilio-ruby', ['~> 5.0'])
    s.add_dependency('twilio-ruby', ['~> 5.0'])
    s.add_dependency('webmock', ['>= 0'])
  end
end
