# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: signalwire 1.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "signalwire".freeze
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["SignalWire Team".freeze]
  s.date = "2019-01-13"
  s.email = "open.source@signalwire.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rubocop.yml",
    "AUTHORS.md",
    "CHANGELOG.md",
    "Dockerfile",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "Makefile",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/signalwire/rest/client.rb",
    "lib/signalwire/sdk.rb",
    "lib/signalwire/sdk/configuration.rb",
    "lib/signalwire/sdk/domain.rb",
    "lib/signalwire/sdk/fax_response.rb",
    "lib/signalwire/sdk/messaging_response.rb",
    "lib/signalwire/sdk/twilio_set_fax.rb",
    "lib/signalwire/sdk/twilio_set_host.rb",
    "lib/signalwire/sdk/voice_response.rb",
    "signalwire.gemspec",
    "spec/signalwire/rest/client_spec.rb",
    "spec/signalwire/rest/integration_spec.rb",
    "spec/signalwire/sdk/configuration_spec.rb",
    "spec/signalwire/sdk/fax_response_spec.rb",
    "spec/signalwire/sdk/messaging_response_spec.rb",
    "spec/signalwire/sdk/voice_response_spec.rb",
    "spec/signalwire/sdk_spec.rb",
    "spec/spec_helper.rb",
    "spec/vcr_cassettes/accounts.yml",
    "spec/vcr_cassettes/applications.yml",
    "spec/vcr_cassettes/get_fax.yml",
    "spec/vcr_cassettes/get_fax_media_instance.yml",
    "spec/vcr_cassettes/get_fax_media_list.yml",
    "spec/vcr_cassettes/list_faxes.yml",
    "spec/vcr_cassettes/local_numbers.yml",
    "spec/vcr_cassettes/recordings.yml",
    "spec/vcr_cassettes/send_fax.yml",
    "spec/vcr_cassettes/toll_free_numbers.yml",
    "spec/vcr_cassettes/transcriptions.yml"
  ]
  s.homepage = "http://github.com/signalwire/signalwire-ruby".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.7.3".freeze
  s.summary = "Ruby client for Signalwire".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<twilio-ruby>.freeze, ["~> 5.0"])
      s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler-audit>.freeze, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<webmock>.freeze, [">= 0"])
      s.add_development_dependency(%q<vcr>.freeze, [">= 0"])
    else
      s.add_dependency(%q<twilio-ruby>.freeze, ["~> 5.0"])
      s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<rubocop>.freeze, [">= 0"])
      s.add_dependency(%q<bundler-audit>.freeze, [">= 0"])
      s.add_dependency(%q<guard-rspec>.freeze, [">= 0"])
      s.add_dependency(%q<webmock>.freeze, [">= 0"])
      s.add_dependency(%q<vcr>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<twilio-ruby>.freeze, ["~> 5.0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<rubocop>.freeze, [">= 0"])
    s.add_dependency(%q<bundler-audit>.freeze, [">= 0"])
    s.add_dependency(%q<guard-rspec>.freeze, [">= 0"])
    s.add_dependency(%q<webmock>.freeze, [">= 0"])
    s.add_dependency(%q<vcr>.freeze, [">= 0"])
  end
end

