# frozen_string_literal: true

require 'minitest/autorun'
require 'rack/test'
require 'json'

ENV['SIGNALWIRE_LOG_MODE'] = 'off'

require_relative '../lib/signalwire'

class AuthAutoGeneratedTest < Minitest::Test
  # Run the block with the basic-auth env vars cleared, restoring them after.
  def without_basic_auth_env
    saved_user = ENV.delete('SWML_BASIC_AUTH_USER')
    saved_pass = ENV.delete('SWML_BASIC_AUTH_PASSWORD')
    yield
  ensure
    ENV['SWML_BASIC_AUTH_USER'] = saved_user if saved_user
    ENV['SWML_BASIC_AUTH_PASSWORD'] = saved_pass if saved_pass
  end

  def test_basic_auth_auto_generated
    without_basic_auth_env do
      creds = SignalWire::AgentBase.new.get_basic_auth_credentials

      assert_equal 2, creds.length
      refute_empty creds[0]
      refute_empty creds[1]
    end
  end

  def test_auto_generated_creds_are_uuid_format
    without_basic_auth_env do
      user, pass = SignalWire::AgentBase.new.get_basic_auth_credentials

      assert_match(/\A[0-9a-f-]{36}\z/, user)
      assert_match(/\A[0-9a-f-]{36}\z/, pass)
    end
  end
end

class AuthExplicitTest < Minitest::Test
  def test_basic_auth_explicit
    agent = SignalWire::AgentBase.new(basic_auth: %w[user pass])

    assert_equal %w[user pass], agent.get_basic_auth_credentials
  end
end

class AuthEnvVarsTest < Minitest::Test
  def test_basic_auth_from_env
    ENV['SWML_BASIC_AUTH_USER']     = 'envuser'
    ENV['SWML_BASIC_AUTH_PASSWORD'] = 'envpass'
    agent = SignalWire::AgentBase.new

    assert_equal %w[envuser envpass], agent.get_basic_auth_credentials
  ensure
    ENV.delete('SWML_BASIC_AUTH_USER')
    ENV.delete('SWML_BASIC_AUTH_PASSWORD')
  end
end

# --- Python parity: get_basic_auth_credentials(include_source) -------
# Mirrors signalwire-python tests around AuthMixin.get_basic_auth_credentials
# returning a 3-tuple including a source label when requested.
class AuthIncludeSourceTest < Minitest::Test
  def test_swml_service_include_source_environment
    ENV['SWML_BASIC_AUTH_USER']     = 'envuser'
    ENV['SWML_BASIC_AUTH_PASSWORD'] = 'envpass'
    svc = SignalWire::SWML::Service.new(name: 'svc')
    user, pass, source = svc.get_basic_auth_credentials(include_source: true)

    assert_equal 'envuser', user
    assert_equal 'envpass', pass
    assert_equal 'environment', source
  ensure
    ENV.delete('SWML_BASIC_AUTH_USER')
    ENV.delete('SWML_BASIC_AUTH_PASSWORD')
  end

  def test_swml_service_include_source_provided
    svc = SignalWire::SWML::Service.new(name: 'svc', basic_auth: %w[user1 pass1])
    user, pass, source = svc.get_basic_auth_credentials(include_source: true)

    assert_equal 'user1', user
    assert_equal 'pass1', pass
    assert_equal 'provided', source
  end

  def test_swml_service_two_tuple_default
    svc = SignalWire::SWML::Service.new(name: 'svc', basic_auth: %w[u p])
    creds = svc.get_basic_auth_credentials

    assert_equal 2, creds.length
  end

  def test_legacy_with_source_alias_still_works
    svc = SignalWire::SWML::Service.new(name: 'svc', basic_auth: %w[u p])
    legacy = svc.get_basic_auth_credentials_with_source

    assert_equal 3, legacy.length
    assert_equal 'u', legacy[0]
    assert_equal 'p', legacy[1]
  end
end

class AuthRackValidationTest < Minitest::Test
  include Rack::Test::Methods

  def app
    @agent = SignalWire::AgentBase.new(basic_auth: %w[testuser testpass])
    @agent.set_prompt_text('Hello')
    @agent.rack_app
  end

  def test_requires_auth
    get '/'

    assert_equal 401, last_response.status
  end

  def test_wrong_auth
    header 'Authorization', "Basic #{['wrong:creds'].pack('m0')}"
    get '/'

    assert_equal 401, last_response.status
  end

  def test_correct_auth
    header 'Authorization', "Basic #{['testuser:testpass'].pack('m0')}"
    get '/'

    assert_equal 200, last_response.status
  end

  def test_health_no_auth_needed
    get '/health'

    assert_equal 200, last_response.status
  end

  def test_ready_no_auth_needed
    get '/ready'

    assert_equal 200, last_response.status
  end
end

class AuthTimingSafeTest < Minitest::Test
  def test_secure_compare_is_used
    assert_respond_to Rack::Utils, :secure_compare,
                      'Rack::Utils.secure_compare must be available for timing-safe auth'
  end

  def test_secure_compare_works
    assert Rack::Utils.secure_compare('hello', 'hello')
    refute Rack::Utils.secure_compare('hello', 'world')
    refute Rack::Utils.secure_compare('short', 'longer_string')
  end
end
