# frozen_string_literal: true

# Aggregator for the generated read-side typed payload modules (SESSION_CHANGESET
# item D). Each subtree is emitted by its own generator:
#   core/swml_verbs_generated/     <- scripts/generate_swml_verbs.py
#   relay/protocol_types_generated/ <- scripts/generate_relay_protocol.py
#   core/post_prompt_generated/     <- scripts/generate_swaig_payloads.py
#   core/swaig_request_generated/   <- scripts/generate_swaig_payloads.py
#   core/swaig_actions_generated/   <- scripts/generate_swaig_payloads.py
#
# These are method-less data classes (a frozen FIELDS constant carrying the wire
# shape); they hold no cross-references, so load order among them is irrelevant.
# This file is HAND-written (a stable require manifest); everything it loads is
# generated + regenerated by the scripts above.

%w[
  core/swml_verbs_generated
  relay/protocol_types_generated
  core/post_prompt_generated
  core/swaig_request_generated
  core/swaig_actions_generated
].each do |rel|
  Dir[File.join(__dir__, rel, '**', '*.rb')].each { |f| require f }
end
