# frozen_string_literal: true

# Spec-derived generated surface: wire keys, folded schema constants, and per-schema
# CRUD/data-class size are preserved verbatim; these cops are pruned per file by the
# generator's rubocop pass to exactly those that fire.
# rubocop:disable Layout/LineLength, Metrics/ClassLength

# Code generated; DO NOT EDIT. Regenerate with the matching scripts/generate_*.py.
#
# schema.json $defs schema 'AiParams'

module SignalWire
  # SignalWire::Core — namespace for this generated data-class tree.
  module Core
    # SignalWire::Core::SwmlVerbsGenerated — namespace for this generated data-class tree.
    module SwmlVerbsGenerated
      # AiParams — generated read-side payload (schema.json $defs schema 'AiParams').
      #
      # Frozen FIELDS maps each snake wire key to its JSON type symbol.
      # Each field also has a zero-arg reader, so a decoded payload can be
      # accessed by name rather than by wire key.
      class AiParams
        FIELDS = {
          'acknowledge_interruptions' => :object,
          'acoustic_eot_gate_prob' => :object,
          'acoustic_eot_trust_prob' => :object,
          'ai_model' => :string,
          'ai_name' => :string,
          'ai_volume' => :object,
          'app_name' => :string,
          'asr_diarize' => :object,
          'asr_params' => :object,
          'asr_smart_format' => :object,
          'asr_speaker_affinity' => :object,
          'attention_escalate_prompt' => :string,
          'attention_timeout' => :object,
          'attention_timeout_prompt' => :string,
          'auth_token' => :string,
          'auto_correct' => :object,
          'azure_stream_first' => :object,
          'azure_tts_key' => :string,
          'background_file' => :string,
          'background_file_loops' => :object,
          'background_file_volume' => :object,
          'barge_functions' => :object,
          'barge_match_string' => :string,
          'barge_min_words' => :object,
          'bill_all_tts' => :object,
          'cache' => :object,
          'call_uuid' => :string,
          'cartesia_key' => :string,
          'cartesia_model' => :string,
          'cartesia_stream_first' => :object,
          'confidence' => :object,
          'conscience' => :string,
          'conversation_id' => :string,
          'conversation_sliding_window' => :object,
          'convo' => :array,
          'debug_webhook_level' => :object,
          'debug_webhook_url' => :string,
          'deepgram_key_override' => :string,
          'deepgram_stream_first' => :object,
          'deepgram_tts_key' => :string,
          'deepgram_url_override' => :string,
          'developer_prompt' => :string,
          'digit_terminators' => :string,
          'digit_timeout' => :object,
          'direction' => :string,
          'double_turn_filler_every_n' => :object,
          'double_turn_filler_min_ms' => :object,
          'double_turn_model' => :string,
          'double_turn_prompt' => :string,
          'double_turn_wait_ms' => :object,
          'double_turns' => :object,
          'eleven_labs_key' => :string,
          'eleven_labs_model' => :string,
          'eleven_labs_similarity' => :object,
          'eleven_labs_stability' => :object,
          'eleven_labs_stream_first' => :object,
          'enable_barge' => :object,
          'enable_inner_dialog' => :object,
          'enable_pause' => :object,
          'enable_text_normalization' => :string,
          'enable_thinking' => :object,
          'enable_turn_detection' => :object,
          'enable_vision' => :object,
          'end_of_speech_timeout' => :object,
          'energy_level' => :object,
          'escalate_after_ms' => :object,
          'escalate_after_turns' => :object,
          'event_webhook_url' => :string,
          'ext' => :string,
          'first_word_timeout' => :object,
          'fish_key' => :string,
          'fish_model' => :string,
          'function_filler_sequence_gap_ms' => :object,
          'function_wait_for_talking' => :object,
          'functions_on_no_response' => :object,
          'grok_key' => :string,
          'groq_tts_key' => :string,
          'hard_stop_prompt' => :string,
          'hard_stop_time' => :string,
          'hold_music' => :string,
          'hold_on_process' => :object,
          'inactivity_timeout' => :object,
          'initial_sleep_ms' => :object,
          'inner_dialog' => :object,
          'inner_dialog_model' => :string,
          'inner_dialog_prompt' => :string,
          'inner_dialog_scorecard' => :object,
          'input_poll_freq' => :object,
          'interrupt_on_noise' => :object,
          'interrupt_prompt' => :string,
          'inworld_apikey' => :string,
          'inworld_key' => :string,
          'inworld_model' => :string,
          'language' => :string,
          'languages_enabled' => :object,
          'lipsync_debug' => :object,
          'llm_diarize_aware' => :object,
          'local_tz' => :string,
          'max_emotion' => :object,
          'max_response_tokens' => :object,
          'min_utterance_ms' => :object,
          'minimax_key' => :string,
          'minimax_model' => :string,
          'mistral_key' => :string,
          'mistral_model' => :string,
          'model' => :string,
          'openai_asr_engine' => :string,
          'openai_azure' => :object,
          'openai_gcloud_version' => :string,
          'openai_stream_first' => :object,
          'openai_tts_key' => :string,
          'openai_tts_url' => :string,
          'outbound_attention_timeout' => :object,
          'pcm_channels' => :object,
          'pcm_rate' => :object,
          'persist_global_data' => :object,
          'pom_format' => :string,
          'provider' => :string,
          'pvt_params' => :string,
          'realtime' => :object,
          'redact_prompt' => :string,
          'rime_apikey' => :string,
          'rime_key' => :string,
          'rime_model' => :string,
          'rime_stream_first' => :object,
          'sample_rate' => :object,
          'save_conversation' => :object,
          'send_single_llm_response' => :object,
          'similarity' => :object,
          'smallest_key' => :string,
          'smallest_model' => :string,
          'speak_when_spoken_to' => :object,
          'speaker' => :string,
          'speech_event_timeout' => :object,
          'speech_gen_quick_stops' => :object,
          'speech_timeout' => :object,
          'speechify_key' => :string,
          'speechify_loudness_normalization' => :object,
          'speechify_model' => :string,
          'speechify_output_format' => :string,
          'speechify_stream_first' => :object,
          'speechify_text_normalization' => :object,
          'speed' => :object,
          'stability' => :object,
          'start_paused' => :object,
          'static_greeting' => :string,
          'static_greeting_no_barge' => :object,
          'stream_first' => :object,
          'streaming' => :object,
          'strict_mode' => :string,
          'summary_mode' => :string,
          'swaig_allow_settings' => :object,
          'swaig_allow_swml' => :object,
          'swaig_post_conversation' => :object,
          'swaig_post_swml_vars' => :object,
          'swaig_set_global_data' => :object,
          'target_first_segment_ms' => :object,
          'text_normalization_far_dir' => :string,
          'thinking_model' => :string,
          'tool_result_distill' => :object,
          'transfer_summary' => :object,
          'transparent_barge' => :object,
          'transparent_barge_max_time' => :object,
          'tts_number_format' => :string,
          'turn_detection' => :object,
          'turn_detection_min_length' => :object,
          'turn_detection_timeout' => :object,
          'turn_filler_every_n' => :object,
          'turn_filler_min_ms' => :object,
          'turn_filler_sources' => :string,
          'url' => :string,
          'utility_model' => :string,
          'vad_config' => :string,
          'video_fps' => :object,
          'video_idle_file' => :string,
          'video_listening_file' => :string,
          'video_scale' => :string,
          'video_talking_file' => :string,
          'vision_model' => :string,
          'voice_name' => :string,
          'vol' => :object,
          'wait_for_user' => :object,
          'wake_prefix' => :string
        }.freeze

        attr_reader :acknowledge_interruptions, :acoustic_eot_gate_prob, :acoustic_eot_trust_prob, :ai_model, :ai_name, :ai_volume, :app_name, :asr_diarize, :asr_params, :asr_smart_format, :asr_speaker_affinity, :attention_escalate_prompt, :attention_timeout, :attention_timeout_prompt, :auth_token, :auto_correct, :azure_stream_first, :azure_tts_key, :background_file, :background_file_loops, :background_file_volume, :barge_functions, :barge_match_string, :barge_min_words, :bill_all_tts, :cache, :call_uuid, :cartesia_key, :cartesia_model, :cartesia_stream_first, :confidence, :conscience, :conversation_id, :conversation_sliding_window, :convo, :debug_webhook_level, :debug_webhook_url, :deepgram_key_override, :deepgram_stream_first, :deepgram_tts_key, :deepgram_url_override, :developer_prompt, :digit_terminators, :digit_timeout, :direction, :double_turn_filler_every_n, :double_turn_filler_min_ms, :double_turn_model, :double_turn_prompt, :double_turn_wait_ms, :double_turns, :eleven_labs_key, :eleven_labs_model, :eleven_labs_similarity, :eleven_labs_stability, :eleven_labs_stream_first, :enable_barge, :enable_inner_dialog, :enable_pause, :enable_text_normalization, :enable_thinking, :enable_turn_detection, :enable_vision, :end_of_speech_timeout, :energy_level, :escalate_after_ms, :escalate_after_turns, :event_webhook_url, :ext, :first_word_timeout, :fish_key, :fish_model, :function_filler_sequence_gap_ms, :function_wait_for_talking, :functions_on_no_response, :grok_key, :groq_tts_key, :hard_stop_prompt, :hard_stop_time, :hold_music, :hold_on_process, :inactivity_timeout, :initial_sleep_ms, :inner_dialog, :inner_dialog_model, :inner_dialog_prompt, :inner_dialog_scorecard, :input_poll_freq, :interrupt_on_noise, :interrupt_prompt, :inworld_apikey, :inworld_key, :inworld_model, :language, :languages_enabled, :lipsync_debug, :llm_diarize_aware, :local_tz, :max_emotion, :max_response_tokens, :min_utterance_ms, :minimax_key, :minimax_model, :mistral_key, :mistral_model, :model, :openai_asr_engine, :openai_azure, :openai_gcloud_version, :openai_stream_first, :openai_tts_key, :openai_tts_url, :outbound_attention_timeout, :pcm_channels, :pcm_rate, :persist_global_data, :pom_format, :provider, :pvt_params, :realtime, :redact_prompt, :rime_apikey, :rime_key, :rime_model, :rime_stream_first, :sample_rate, :save_conversation, :send_single_llm_response, :similarity, :smallest_key, :smallest_model, :speak_when_spoken_to, :speaker, :speech_event_timeout, :speech_gen_quick_stops, :speech_timeout, :speechify_key, :speechify_loudness_normalization, :speechify_model, :speechify_output_format, :speechify_stream_first, :speechify_text_normalization, :speed, :stability, :start_paused, :static_greeting, :static_greeting_no_barge, :stream_first, :streaming, :strict_mode, :summary_mode, :swaig_allow_settings, :swaig_allow_swml, :swaig_post_conversation, :swaig_post_swml_vars, :swaig_set_global_data, :target_first_segment_ms, :text_normalization_far_dir, :thinking_model, :tool_result_distill, :transfer_summary, :transparent_barge, :transparent_barge_max_time, :tts_number_format, :turn_detection, :turn_detection_min_length, :turn_detection_timeout, :turn_filler_every_n, :turn_filler_min_ms, :turn_filler_sources, :url, :utility_model, :vad_config, :video_fps, :video_idle_file, :video_listening_file, :video_scale, :video_talking_file, :vision_model, :voice_name, :vol, :wait_for_user, :wake_prefix
      end
    end
  end
end
# rubocop:enable Layout/LineLength, Metrics/ClassLength
